### ISSUE TITLE
Examples link not working

### ISSUE THREAD

**Issue by didimitrie** [philipbelesky/webhopper#1]
Just a quick heads up, points to a 404 :)

**Comment by philipbelesky** [comment]
Hey Dimitie, I thought you might be interested in this, but I was holding off on bringing it to your attention until it's bit more finished. Currently its in a very early stage and development is largely on hold for a month or two. I've updated the README to clarify this and remove the examples link.

That said if you want to checkout the examples as-is the README instructions under "Development (Styles/Markup Documentation)" should bring them up on a local copy.

**Comment by didimitrie** [comment]
Hehe, don't underestimate the power of stalking :) cool. I'll have a poke soon, as the new speckle is ready to hatch and this would be a useful thing to have!
